arch:
- aarch64
backup_exclude:
- '*/logs'
codenotary: codenotary@frenck.dev
description: Moded Manage Nginx proxy hosts with a simple, powerful interface
hassio_api: true
image: ghcr.io/hassio-addons/nginxproxymanager/{arch}
init: false
map:
- ssl:rw
- backup:rw
name: Nginx Proxy Manager
ports:
  4443/tcp: 443
  8080/tcp: 80
  8181/tcp: 81
ports_description:
  4443/tcp: HTTPS/SSL Entrance port
  8080/tcp: HTTP Entrance port
  8181/tcp: Proxy management web interface
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  reset_database: bool?
services:
- mysql:need
slug: nginxproxymanager
url: https://github.com/lockevod/home-assistant-addons/addon-nginx-proxy-manager
version: 0.1
webui: http://[HOST]:[PORT:8181]
